version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    env_file: .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    hostname: redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/home/app/web
      - media_volume:/home/app/web/media
    command: [ "sh","./start-celery-worker" ]

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /tmp/wkhtmltopdf/:/tmp/wkhtmltopdf/
volumes:
  media_volume:
  postgres_data:
  static_volume:

