version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    env_file: .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: "backend"
    restart: always
    build:
      context: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    command: [ "sh","./start" ]
  nginx:
    build: ./nginx
    env_file: ./.env
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    restart: always
volumes:
  nginx_conf:
  media_volume:
  postgres_data:
  static_volume:

