# Generated by Django 4.2 on 2023-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=100)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("client", "client"), ("kitchen", "kitchen")],
                        max_length=10,
                    ),
                ),
                ("point_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Printer",
                "verbose_name_plural": "Printers",
                "ordering": ["name"],
            },
        ),
    ]
