# Generated by Django 4.2 on 2023-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="api_key",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
