# Generated by Django 4.2 on 2023-09-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("printer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("client", "client"), ("kitchen", "kitchen")],
                        max_length=10,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("rendered", "rendered"),
                            ("printed", "printed"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="checks/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="printer.printer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check",
                "verbose_name_plural": "Checks",
                "ordering": ["-created_at"],
            },
        ),
    ]
