# Generated by Django 4.2 on 2023-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0002_alter_check_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="type",
            field=models.CharField(max_length=10),
        ),
    ]
